name: Build
on:
  push:
    branches:
    - f.*
    - main
jobs:
  build:
    runs-on: windows-latest
    steps: 
      - name: Download Code
        uses: actions/checkout@v4

      - name: Install DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Compile Code
        run: |
          cd ISC-AutoLoader
          ls
          dotnet clean
          dotnet restore ISC-AutoLoader.sln
          dotnet publish ISC-AutoLoader.sln --source ./ --configuration release --property WarningLevel=0
          
      - name: Publish Code
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ./ISC-AutoLoader/ISC-AutoLoader/bin/Release/net8.0/publish/
